### ISSUE TITLE
MQTT authorisation

### ISSUE THREAD

**Issue by chuank** [Qatja/processing#3]
Thanks for providing this library for processing users!

Do you have plans to add MQTT authorisation support?

**Comment by agoransson** [comment]
Hey, thanks for trying it out. I do have plans for updating this library, mostly the android part. However, I believe that authorization is implementation specific, there's no "rulebook" on how this is done in MQTT. I know HiveMQ has a plugin for authorization, while mosquitto has none. If you look at Xively's implementation you're appending an OAuth token in all the packages you send to authorize them. I think WebSphere has their very own role-based system - I've not tested this lib with websphere yet so I'm not sure of the details there.

So, this really is dependent on the broker/service you're using and it might be very complicated (or impossible) to support a generic authorization mechanism in this lib right now. I'll put some thought into it, but I can't promise a timely solution for you.

**Comment by chuank** [comment]
Thanks @agoransson for the feedback and the extra information on authentication layers used by various brokers – it was a good read on the various authentication layers used by various brokers.

I have been using mosquitto 3.1, which supports a basic username/password authentication in the CONNECT packet as defined by the MQTT protocol:

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718116

I was wondering if qatja will support this basic username/password authentication – since it's already part of the MQTT 3.1 specification. Perhaps instantiating the qatja object with the option of including a username+password?

It's not very secure, but great for testing small, non-critical setups?

**Comment by agoransson** [comment]
Ahh, the MQTT authentication. Sure, that should already be supported. =)

Note though that this lib only works with 3.1.1 for now, I've had ideas about making it backwards compatible but decided against it when building it (but it should be quite easy to make it backwards compatible by compiling it yourself, just need to change some header information in a package or two).


Here's some untested code that should work for the username/password authentication.

```java
Qatja client = new Qatja(this);
client.setUsername("myusername");
client.setPassword("mypassword");
client.connect();
```

I think that should do the trick for the basic MQTT auth.

**Comment by chuank** [comment]
argh, silly me! I should have looked closer... thanks again!

**Comment by agoransson** [comment]
No problem. =)

(It's not really well documented, sorry about that)

**Comment by chuank** [comment]
If i may add, updating your compiled processing library to include the latest changes will be much appreciated – your `www.santiclaws.se/qatja/Qatja.zip` link posted on README.md points to an older build that might confuse folks trying out MQTT on P5 – the library manager in Processing is also pointing to the older version of qatja/processing.

Regards

**Comment by agoransson** [comment]
Of course you may add =)

Thanks for pointing this out, I'll build a new version a.s.a.p.
